// GENERATED by scripts/build-bunny-config.mjs — do not edit by hand.
// Re-run after uploading/changing videos: node scripts/build-bunny-config.mjs
// Bunny is the source of truth; captions are fetched live (not stored here).
window.JM_BUNNY_CONFIG = {
  "cdn": "vz-9047a62b-75b.b-cdn.net",
  "videos": {
    "bf493832-51f2-4fe2-8612-66ceb5d3c2d5": {
      "videoId": "2ietmqwkan",
      "title": "Apply Page VSL",
      "poster": "thumbnail_6fd4dfc6.jpg",
      "captions": "en",
      "chapters": []
    },
    "df3f8a15-662a-4abd-beec-6ff2fd1ae312": {
      "videoId": "df3f8a15-662a-4abd-beec-6ff2fd1ae312",
      "title": "Business Breakthrough Challenge — Day 1: The Ceiling",
      "poster": "thumbnail.jpg",
      "captions": "en",
      "chapters": []
    },
    "4f3aa4af-d972-4a60-ab8f-1b531079ff44": {
      "videoId": "4f3aa4af-d972-4a60-ab8f-1b531079ff44",
      "title": "Business Breakthrough Challenge — Day 1: The Ceiling",
      "poster": "thumbnail.jpg",
      "captions": "en",
      "chapters": []
    },
    "7eb243ed-b0c9-4054-a432-c11e2cb009ca": {
      "videoId": "7eb243ed-b0c9-4054-a432-c11e2cb009ca",
      "title": "Business Breakthrough Challenge VIP — Day 1 Q&A",
      "poster": "thumbnail.jpg",
      "captions": "en",
      "chapters": []
    },
    "a1f94ac2-724c-427f-a21a-8b6e557de13a": {
      "videoId": "ufmx6s8p7w",
      "title": "Dana Fradella Testimonial",
      "poster": "thumbnail_38412ff5.jpg",
      "captions": "en",
      "chapters": []
    },
    "6fa7e473-cd2b-4904-afec-a6afd6322aac": {
      "videoId": "birsm04zwz",
      "title": "Effortless Masterclass",
      "poster": "thumbnail_36e4f040.jpg",
      "captions": "en",
      "chapters": [
        {
          "time": 0,
          "label": "The Shift from Striving to Effortless Growth"
        },
        {
          "time": 144,
          "label": "Training Agenda and Community Invitation"
        },
        {
          "time": 452,
          "label": "The Paradox of Hard Work in Business"
        },
        {
          "time": 629,
          "label": "The Fear-Based Paradigm of Effort"
        },
        {
          "time": 915,
          "label": "Identifying Patterns of Over Efforting"
        },
        {
          "time": 1772,
          "label": "Three Levels of Consciousness in Business"
        },
        {
          "time": 2472,
          "label": "Intellectual Consciousness: The Shift to Strategy"
        },
        {
          "time": 2826,
          "label": "Intuitive Consciousness: Embracing Flow"
        },
        {
          "time": 3055,
          "label": "Emily's Transformation Journey"
        },
        {
          "time": 3196,
          "label": "Exploring Intuitive Consciousness"
        },
        {
          "time": 3451,
          "label": "The Power of Magnetic Energy"
        },
        {
          "time": 3631,
          "label": "The Birth of a New Idea"
        },
        {
          "time": 3798,
          "label": "Effortless Business Growth"
        },
        {
          "time": 4551,
          "label": "The Essence of Intuitive Consciousness"
        },
        {
          "time": 4768,
          "label": "Invitation to the Collective Mastermind"
        },
        {
          "time": 5170,
          "label": "Integrating Strategy and Spirit"
        },
        {
          "time": 5445,
          "label": "The Call to Action"
        },
        {
          "time": 5948,
          "label": "Balancing Intuitive and Intellectual Consciousness"
        },
        {
          "time": 6207,
          "label": "The River and Banks Analogy"
        }
      ]
    },
    "e2787fb7-946e-4d19-abd7-9dca76bd1ae6": {
      "videoId": "catuo8tlk0",
      "title": "Emily Hill Testimonial",
      "poster": "thumbnail_3561a807.jpg",
      "captions": "en",
      "chapters": []
    },
    "83ed7fd6-5c03-43f2-b4c6-6db3e79840b9": {
      "videoId": "kvtz80f3pw",
      "title": "Expansion Retreat Testimonials 2",
      "poster": "thumbnail_c3193d38.jpg",
      "captions": "en",
      "chapters": [
        {
          "time": 0,
          "label": "Transformative Weekend Experience"
        },
        {
          "time": 30,
          "label": "Awakening and Business Integration"
        },
        {
          "time": 67,
          "label": "Encouragement to Take Action"
        }
      ]
    },
    "e45b6fc7-974f-478c-8c98-2aaa18108199": {
      "videoId": "c0mfcixd8m",
      "title": "Expansion Retreat Testimonials 3",
      "poster": "thumbnail_8a10930d.jpg",
      "captions": "en",
      "chapters": [
        {
          "time": 0,
          "label": "Initial Hesitations and Discoveries"
        },
        {
          "time": 59,
          "label": "Transformative Experience of Connection"
        }
      ]
    },
    "49a4207c-45ef-41b2-b0d7-582c9af8dff5": {
      "videoId": "7wxnrylt2d",
      "title": "Expansion Retreat Testimonials 4",
      "poster": "thumbnail_1454657b.jpg",
      "captions": "en",
      "chapters": [
        {
          "time": 0,
          "label": "Transformative Experience and Call to Action"
        }
      ]
    },
    "7ed58506-423f-427b-b405-3795f2ecbb75": {
      "videoId": "pikksmoxf3",
      "title": "Expansion Retreat Testimonials 5",
      "poster": "thumbnail_b54f6bbb.jpg",
      "captions": "en",
      "chapters": [
        {
          "time": 0,
          "label": "Transformative Coaching Experience"
        }
      ]
    },
    "98ad4391-4cb4-4e8b-8a1f-3a8adfacddd2": {
      "videoId": "x0tlj5qthd",
      "title": "Federica Prayer Testimonial",
      "poster": "thumbnail_00ef45f9.jpg",
      "captions": "en",
      "chapters": []
    },
    "def07aa3-1cf7-432a-be88-c43b7f5105fc": {
      "videoId": "ef8xvmcqvf",
      "title": "Garret Kusch Testimonial",
      "poster": "thumbnail_4446c609.jpg",
      "captions": "en",
      "chapters": []
    },
    "5a38c245-f511-48e5-8ffb-b4efd1e4168d": {
      "videoId": "g8055phors",
      "title": "Meaghan Long Testimonial",
      "poster": "thumbnail_fb17b1f2.jpg",
      "captions": "en",
      "chapters": []
    },
    "1285aab9-f766-415b-9dcb-27847e8d4a13": {
      "videoId": "pwgrduvffm",
      "title": "Post-Purchase Video",
      "poster": "thumbnail_f59b0142.jpg",
      "captions": "en",
      "chapters": []
    },
    "c921514d-99e3-48f3-875a-704bdb5c4d58": {
      "videoId": "zosvj2ru1y",
      "title": "Resonance Masterclass (2.0)",
      "poster": "thumbnail_6c716c27.jpg",
      "captions": "en",
      "chapters": [
        {
          "time": 0,
          "label": "Intro"
        },
        {
          "time": 61,
          "label": "What is resonance?"
        },
        {
          "time": 304,
          "label": "Marketing as conversion"
        },
        {
          "time": 622,
          "label": "Marketing as resonance"
        },
        {
          "time": 1175,
          "label": "Before vs. after example"
        },
        {
          "time": 1354,
          "label": "Open coaching"
        },
        {
          "time": 1722,
          "label": "Invitation"
        }
      ]
    },
    "12dca8f1-fbd5-4b44-9b7f-b450197677d7": {
      "videoId": "wt38b0yrda",
      "title": "Resonance Masterclass Clip 1 - 2 Goals Of Marketing",
      "poster": "thumbnail_9b981898.jpg",
      "captions": "en",
      "chapters": []
    },
    "8c48235d-020f-4860-ae3e-d75b4e40ba34": {
      "videoId": "9rp4agj0i0",
      "title": "Resonance Masterclass Clip 2 - Content Examples",
      "poster": "thumbnail_4265517e.jpg",
      "captions": "en",
      "chapters": []
    },
    "d7b7080c-ccd1-49a5-8b69-8b9e0c4904b1": {
      "videoId": "ncvrwu0082",
      "title": "Sold Out - Day 1 Live Cut",
      "poster": "thumbnail_532db801.jpg",
      "captions": "en",
      "chapters": [
        {
          "time": 0,
          "label": "Introduction to the Kickoff Call"
        },
        {
          "time": 202,
          "label": "Setting the Tone for Sales"
        },
        {
          "time": 396,
          "label": "Pulse Check on Selling Mindset"
        },
        {
          "time": 634,
          "label": "Reframing Sales Perspectives"
        },
        {
          "time": 845,
          "label": "The Journey of Sales Transformation"
        },
        {
          "time": 1028,
          "label": "Block One: Mindset Shift in Sales"
        },
        {
          "time": 1466,
          "label": "Block Two: Commitment and Change"
        },
        {
          "time": 1886,
          "label": "Block Three: The Joy of Buying"
        },
        {
          "time": 2230,
          "label": "Block Four: The Power of Action"
        },
        {
          "time": 2562,
          "label": "Block Five: Conversations Over Automation"
        },
        {
          "time": 2774,
          "label": "Overcoming Automation Myths"
        },
        {
          "time": 2946,
          "label": "Identifying Effective Strategies"
        },
        {
          "time": 3284,
          "label": "The Importance of Proactive Selling"
        },
        {
          "time": 3498,
          "label": "Introducing the Sold Out Leaderboard"
        },
        {
          "time": 3850,
          "label": "Prizes and Incentives for Participation"
        },
        {
          "time": 4744,
          "label": "VIP Sales Intensive Offer"
        },
        {
          "time": 4932,
          "label": "Next Steps and Ongoing Support"
        }
      ]
    },
    "c08704a3-65af-4455-80b2-2e2721f2d5cb": {
      "videoId": "qyyys9a53h",
      "title": "Sold Out - Day 2 Live Cut",
      "poster": "thumbnail_8a7403a0.jpg",
      "captions": "en",
      "chapters": [
        {
          "time": 0,
          "label": "Introduction and Welcome"
        },
        {
          "time": 155,
          "label": "Encouragement for Participation"
        },
        {
          "time": 244,
          "label": "Sharing Experiences in Conversations"
        },
        {
          "time": 331,
          "label": "Key Sales Framework Introduction"
        },
        {
          "time": 487,
          "label": "Understanding the Concept of the Gap"
        },
        {
          "time": 782,
          "label": "The Importance of Perception in Sales"
        },
        {
          "time": 952,
          "label": "Identifying the Lack of Urgency"
        },
        {
          "time": 1104,
          "label": "Becoming a Gap Finder"
        },
        {
          "time": 1624,
          "label": "Common Mistakes in Sales Conversations"
        },
        {
          "time": 1802,
          "label": "Framework for Eliciting the Gap"
        },
        {
          "time": 2014,
          "label": "Live Demonstration of the Framework"
        },
        {
          "time": 2763,
          "label": "Reflection on the Demonstration"
        },
        {
          "time": 2997,
          "label": "Bridging the Gap in Sales"
        },
        {
          "time": 3125,
          "label": "Navigating Conversations for Client Acquisition"
        },
        {
          "time": 3262,
          "label": "Determining Depth in Conversations"
        },
        {
          "time": 3412,
          "label": "Handling Objections in Sales Calls"
        },
        {
          "time": 3821,
          "label": "Maintaining Leadership in Sales Conversations"
        },
        {
          "time": 3935,
          "label": "Preparing for Future Conversations"
        },
        {
          "time": 4094,
          "label": "Building a Supportive Community for Growth"
        }
      ]
    },
    "5548ca65-891e-4c25-ba82-162f31d59aac": {
      "videoId": "7d7q3zfpev",
      "title": "Sold Out - Day 3 Live Cut",
      "poster": "thumbnail_1a05d090.jpg",
      "captions": "en",
      "chapters": [
        {
          "time": 0,
          "label": "Community Growth and Achievements"
        },
        {
          "time": 104,
          "label": "Engagement and Feedback"
        },
        {
          "time": 336,
          "label": "A Personal Story of Sales Challenges"
        },
        {
          "time": 632,
          "label": "The Lone Wolf Mentality"
        },
        {
          "time": 1017,
          "label": "Decisions from Scarcity vs. Abundance"
        },
        {
          "time": 1379,
          "label": "Building from Safety vs. Abundance"
        },
        {
          "time": 1949,
          "label": "The Indecision Mirror"
        },
        {
          "time": 2264,
          "label": "The Preparation Illusion"
        },
        {
          "time": 3107,
          "label": "Integrating Sales and Marketing Strategies"
        },
        {
          "time": 3233,
          "label": "Invitation to Join the Collective Mastermind"
        },
        {
          "time": 3715,
          "label": "Transformation Through Community"
        },
        {
          "time": 3830,
          "label": "Ongoing Engagement and Support"
        }
      ]
    },
    "c05e987d-3646-452e-a6f3-1a8e1ed3bb37": {
      "videoId": "ltajjoq9hq",
      "title": "Sold Out VSL",
      "poster": "thumbnail_cfdd9b7b.jpg",
      "captions": "en",
      "chapters": []
    },
    "f79f0527-5dd3-4950-9c44-73829f09b7ed": {
      "videoId": "hlntpnigew",
      "title": "Zach Bloom Testimonial",
      "poster": "thumbnail_c1927673.jpg",
      "captions": "en",
      "chapters": []
    }
  }
};
